id: nlp-contextual-targeting
name: NLP -> Contextual Targeting
description: Textual search using text embeddings and cosine similarity instead of
  directly comparing the text
is_active: false
project_type: 8
param_groups:
- name: parameters
  params:
  - name: dataset
    description: Dataset id that is used for fetching dataset from coretex.
    value: null
    data_type: dataset
    required: true
  - name: modelUrl
    description: Deepspeech model URL.
    value: ''
    data_type: str
    required: true
  - name: modelScorerUrl
    description: Deepspeech model amplifier URL.
    value: ''
    data_type: str
    required: true
  - name: batchSize
    description: Chunks of bytes on which transcriber will run
    value: 8196
    data_type: int
    required: true
  - name: target
    description: Text that will be searched for in the transcription/text.
    value: I've been traveling across the country
    data_type: str
    required: true
