id: 9c2cd862-ca76-4a93-ac1d-906c6e78a869
name: Microbiome Forensics -> Region Separation
description: Task template for separating short sequence read files based on the hypervariable
  regions they cover
is_active: true
project_type: 11
param_groups:
- name: inputs
  params:
  - name: dataset
    description: Coretex dataset holding sequence read files which will be separated
      into groups by hypervariable regions
    value: null
    data_type: dataset
    required: true
  - name: referenceDataset
    description: (If useBacteriaLib is true this will be ignored) Dataset with reference
      sequences on which alignment will be performed
    value: null
    data_type: dataset
    required: true
  - name: referenceDatasetIndexed
    description: '(If useBacteriaLib is true this will be ignored) Wheather the provided
      referenceDataset dataset has indexes insted of raw sequences. In this case all
      the sequences have to be in one sample and the stucture for each file needs
      to be like this: {sample}/{prefix}/{prefix}.ext (the folder name for each reference
      sequence has to be the name of the indexing prefix of the files within)'
    value: false
    data_type: bool
    required: true
- name: outputs
  params:
  - name: separatedDataset
    description: The dataset to which the separated files will be uploaded
    value: null
    data_type: dataset
    required: false
- name: parameters
  params:
  - name: separationGroups
    description: A list of names for directories to which the input files will be
      separated (The number of items in this list will determine the number of regions
      for separation)
    value:
    - V1V3
    - V3V5
    data_type: list[str]
    required: true
  - name: separationThresholds
    description: These values will serve as thresholds between separation regions
      (the length of this list has to be by one less then the length of separationGroups)
    value:
    - 450
    data_type: list[int]
    required: true
