id: adf92e59-35a6-47b9-b526-0d6615d74b4e
name: Model Comparison
description: Compares provided Coretex models
is_active: false
project_type: 8
param_groups:
  - name: inputs
    params:
      - name: models
        description: List of Coretex models that will be used for comparison.
        value: null
        data_type: list[model]
        required: true
  - name: outputs
    params:
      - name: outputModel
        description: Model with highest accuracy from the list of provided Coretex models.
        value: null
        data_type: model
        required: false
