id: model-comparison
name: Model Comparison
description: "Task that takes a list of Coretex models as input and compares them by their accuracy. Output of the task is the model with highest accuracy."
is_active: true
project_type: 8
param_groups:
  - name: inputs
    params:
      - name: models
        description: List of Coretex models that will be used for comparison.
        value: null
        data_type: list[model]
        required: true
  - name: outputs
    params:
      - name: outputModel
        description: Model with highest accuracy from the list of provided Coretex models.
        value: null
        data_type: model
        required: false
