id: 34716866-2831-454a-b358-973326b4e16a
name: Microbiome Forensics -> Body Site Prediction - XGBoost
description: "Body site prediction task template is based on XGBoost (gradient\r\n\
  boosting) algorithm.\r\n\r\nThis template takes BioInformatics sequence taxonomic\
  \ compositions\r\nand traines a model which is capable of predicting body site (from\
  \ which the\r\nsample originates) based on the sample taxonomic composition.\r\n\
  \r\nData provided to the model can be in either of these two formats:\r\n    - MBA\
  \ (Microbiome Atlas)\r\n    - ForBiome (Microbiome Forensics Institute Zurich)\r\
  \n\_\r\nInput of the model is a 2D matrix with input shape [samples, uniqueTaxons]\
  \ where:\r\n    - samples: number of samples in the dataset,\r\n    - uniqueTaxons:\
  \ number of unique taxons in the dataset\r\n\r\nOutput of the model is a 1D array\
  \ with integers representing different bodysites.\r\n\r\nExpected TaskRun runtime\
  \ on CPU with ~1 GB of MBA data is ~4m 22s.\r\nExpected TaskRun runtime on GPU with\
  \ ~1 GB of MBA data is ~3m 19s.\r\n\r\nSystem specifications on which the TaskRuns\
  \ were run:\r\n    - CPU: AMD Ryzen 7 1800X Eight-Core Processor\r\n    - GPU: Nvidia\
  \ GeForce GTX 1080 Ti 12 GB VRAM\r\n    - RAM: 32 GB 2666 MHz DDR4\r\n\r\nTaskRun\
  \ parameters:\r\n    - Percentile: 100\r\n    - Quantize: False\r\n    - Epochs:\
  \ 100\r\n    - Early stopping: 0\r\n    - Cache: False\r\n    - Enviromnment: Clean"
project_type: 11
is_active: true
jobs:
  microbiome-forensics-body-site-prediction-xgboost:
    template_id: 348092ce-cdb9-412c-a777-69154bb5f160
