id: dd23263b-0df7-4309-9d1a-a77b1efe4d9c
name: Microbiome Forensics -> Body Site Prediction - LSPIN
description: "Bodysite Classifier - LSPIN task template uses a neural network architecture\n\
  based on the paper \"Locally Sparse Neural Networks for Tabular Biomedical Data\u201D\
  ,\nwhich is a multilayer perceptron with gating layers.\n\nThis template takes BioInformatics\
  \ sequence taxonomic compositions\nand traines a model which is capable of predicting\
  \ body site (from which the\nsample originates) based on the sample taxonomic composition.\n\
  \nData provided to the model can be in either of these two formats:\n    - MBA (Microbe\
  \ Atlas)\n    - ForBiome (Forensics Microbiome Database, maintained by Microbiome\
  \ Forensics Institute Zurich)\n\nInput of the model is a 2D matrix with input shape\
  \ [samples, uniqueTaxons] where:\nsamples: number of samples in the dataset\nuniqueTaxons:\
  \ number of unique taxons in the dataset\n\nOutput of the model is a 1D array with\
  \ integers representing different bodysites.\n\nExpected TaskRun runtime on GPU\
  \ with 1GB of MBA data is ~30minutes.\n\nSystem specifications on which the TaskRuns\
  \ were run:\n    - CPU: AMD Ryzen 7 1800X Eight-Core Processor\n    - GPU: Nvidia\
  \ GeForce GTX 1080 Ti 12 GB VRAM\n    - RAM: 32 GB 2666 MHz DDR4\n\nTaskRun parameters:\n\
  Batch size: 512\nBuffer size: 512\nHIdden layers: [256, 256, 128]\nActivation function:\
  \ tanh\nBatch norm: False\nCache: False\nEnviromnment: Clean"
project_type: 11
is_active: true
jobs:
  microbiome-forensics-body-site-prediction-lspin:
    template_id: 19110f48-c05d-42cc-8ae2-5454e7788418
