id: 6a8a4308-5b84-432b-814c-b464aeac651c
name: Object Detection (YoloV5)
description: "Object Detection task template is based on YoloV5 model (https://github.com/ultralytics/yolov5).\r\
  \nYoloV5 is a state of the art (SOTA) model for running Object Detection on images.\r\
  \n\r\nInput of the model is an RGB image with pixel values normalized in range (0\
  \ - 1).\r\nTraining (Torch model) input shape is [batchSize, channels, height, width]\
  \ where:\r\n    - batchSize: number of images in a given batch\r\n    - channels:\
  \ number of image channels, and currently it is set to 3 which represents RGB image\r\
  \n    - height: image height\r\n    - width: image width\r\n\r\nExported (Tensorflow\
  \ / JS model) input shape is [batchSize, height, width, channels]\r\n\r\nOutput\
  \ of the model is an array of 4 different values:\r\n    - Index 0: Bounding boxes\r\
  \n    - Index 1: Scores (range: 0 - 1) - how confident model is for the detected\
  \ class\r\n    - Index 2: Class of the detection\r\n    - Index 3: Number of (valid)\
  \ detections after performing NMS (Non-maximum suppression)\r\n\r\nExpected TaskRun\
  \ runtime on CPU is ~36m 17s.\r\n    - CPU: 2.3GHz 8-core 9th-generation Intel Core\
  \ i9\r\n    - RAM: 16 GB 2667 MHz DDR4\r\n\r\nExpected TaskRun runtime on GPU is\
  \ ~7m 49s. System specifications:\r\n    - CPU: AMD Ryzen 7 1800X Eight-Core Processor\r\
  \n    - GPU: Nvidia GeForce GTX 1080 Ti 12 GB VRAM\r\n    - RAM: 32 GB 2666 MHz\
  \ DDR4\r\n\r\nTaskRun parameters:\r\n    - Image count: 91\r\n    - Epochs: 10\r\
  \n    - Batch size: 16\r\n    - Image size: 640x640\r\n    - Environment: Clean\r\
  \n"
project_type: 1
is_active: true
jobs:
  object-detection-yolov5-:
    template_id: c3256ce2-700e-40a8-9a61-4dfa407de078
