id: qiime2-alpha-beta-diversity-workflow
name: Qiime2 -> Alpha & Beta diversity
description: Workflow from denoise sequence reads to feature table generation, OTU clustering,
  taxonomic analysis, phylogenetic tree generation and alpha and beta diversity analysis
project_type: 11
is_active: true
jobs:
  step-4-otu-clustering:
    template_id: qiime2-otu-clustering

  step-5-taxonomic-analysis:
    template_id: qiime2-taxonomic-analysis

  step-6-phylogenetic-diversity-analysis:
    template_id: qiime2-phylogenetic-diversity-analysis

  step-7-alpha-and-beta-diversity-analysis:
    template_id: qiime2-alpha-beta-diversity-analysis
    param_groups:
      inputs:
        dataset: step-6-phylogenetic-diversity-analysis.outputDataset
