id: 5451638b-ab1b-4083-8acc-6d46ccbb644f
name: 'Qiime2 -> Step 2: Demultiplexing sequences'
description: 'Multiple samples can be pooled into a single sequencing run. This reduces
  the time and

  cost of sequencing. To differentiate between these samples, each of them had a unique

  barcode injected into them before sequencing them.


  Before doing any kind of analysis on sequence data, you first need to extract

  the sample data from sequences associated with every of the barcodes. This template

  is used for doing that.


  The input is a dataset which contains miltiplexed sequences imported to Qiime2

  with the EMP Protoacol. This can be done using the Import task form the Coretex

  Qiime templates


  Output data is demultiplexed sequences which contains a separate "fastq" file

  for every sample.'
project_type: 11
is_active: true
jobs:
  qiime2-step-2-demultiplexing-sequences:
    template_id: 72fee3bd-33d9-42fa-a5da-e41fefc0ab2d
