id: a8d6cba8-d1b5-4f90-9ef5-296931ee1a1e
name: 'Qiime2 -> Step 5: Taxonomic Analysis'
description: "Taxonomic analysis is used to extract taxonomy (taxonomic composition)\
  \ of\nthe samples. It achieves this by using a ML model for this process.\n\nThe\
  \ info that gets extracted is also visualized, so you\ncan easily explore multiple\
  \ levels of taxonomic composition of the samples.\n\nInput data is:\n    - File\
  \ which contains metadata about samples\n    - ML model which predicts taxonomic\
  \ composition of a\n      given sequence\n    - Filtered sequence data generated\
  \ by the third task in the Coretex\n      Qiime pipeline, DADA2\n\nOutput data is\
  \ the taxonomic composition of the provided samples."
project_type: 11
is_active: true
jobs:
  qiime2-step-5-taxonomic-analysis:
    template_id: 0b2b27f3-2df0-4d61-a902-15e54cc1a81d
