id: qiime2-full-workflow
name: Qiime2 -> Full Workflow
description: Workflow from raw multiplexed or demultiplexed sequence reads to feature
  table generation, OTU clustering, taxonomic analysis, phylogenetic tree generation
  and alpha and beta diversity analysis
project_type: 11
is_active: true
jobs:
  step-1-import:
    template_id: qiime2-import

  step-2-demultiplexing-sequences:
    template_id: qiime2-demultiplexing-sequences
    param_groups:
      inputs:
        dataset: step-1-import.outputDataset

  step-3-dada2-denoising:
    template_id: qiime2-dada2-denoising
    param_groups:
      inputs:
        dataset: step-2-demultiplexing-sequences.outputDataset

  step-4-otu-clustering:
    template_id: qiime2-otu-clustering
    param_groups:
      inputs:
        dataset: step-3-dada2-denoising.outputDataset

  step-5-taxonomic-analysis:
    template_id: qiime2-taxonomic-analysis
    param_groups:
      inputs:
        dataset: step-3-dada2-denoising.outputDataset
        importedDataset: step-2-demultiplexing-sequences.outputDataset

  step-6-phylogenetic-diversity-analysis:
    template_id: qiime2-phylogenetic-diversity-analysis
    param_groups:
      inputs:
        dataset: step-3-dada2-denoising.outputDataset

  step-7-alpha-and-beta-diversity-analysis:
    template_id: qiime2-alpha-beta-diversity-analysis
    param_groups:
      inputs:
        dataset: step-6-phylogenetic-diversity-analysis.outputDataset
        importedDataset: step-2-demultiplexing-sequences.outputDataset
        denoisedDataset: step-3-dada2-denoising.outputDataset
