id: e4bbfacf-df8e-405b-8819-da50a4e6a52f
name: 'Qiime2 -> Step 4: OTU Clustering'
description: 'This task uses vsearch to perform OTU clustering with the de novo method.


  OTU stands for "Operational Taxonomic Unit." OTU clustering involves grouping

  similar DNA or RNA sequences together based on a predefined sequence similarity

  threshold. The similarity threshold is typically set at a certain percentage (e.g.,
  97%)

  of sequence identity. Sequences that share this level of

  similarity are grouped into the same OTU.


  The input is the dataset created by the third task in the Coretex Qiime Pipeline,

  DADA2. What gets used for the clustering is the feature table.


  The output is a BIOM file with OTUs.'
project_type: 11
is_active: true
jobs:
  qiime2-step-4-otu-clustering:
    template_id: c18cabc7-4098-487e-acb3-449177f33e53
