id: phyloseq-full-workflow
name: Phyloseq -> Full Workflow
description: Workflow for cleaning the data using DADA2 and generating phylogenetic
  tree based on the cleaned data then running Alpha & Beta diversity analyses.
project_type: 11
is_active: true
jobs:
  step-1-dada2-and-phylogenetic-tree:
    template_id: phyloseq-dada2-phylogenetic-tree

  step-2-alpha-and-beta-diversity-analysis:
    template_id: phyloseq-alpha-beta-diversity-analysis
    param_groups:
      inputs:
        dataset: step-1-dada2-and-phylogenetic-tree.outputDataset
