id: 413dd10f-4d4f-4f6d-aa91-662c58768546
name: Document OCR
description: This task template performs original character recognition (OCR) on documents
is_active: true
project_type: 1
param_groups:
- name: inputs
  params:
  - name: dataset
    description: Dataset with document images.
    value: null
    data_type: dataset
    required: true
  - name: segmentationModel
    description: Image segmentation model.
    value: null
    data_type: model
    required: true
  - name: objectDetectionModel
    description: Object detection model.
    value: null
    data_type: model
    required: true
