id: synthetic-image-generator
name: Synthetic Image Generator
description: This task stitches images onto background images in random locations,
  while applying rotation and scaling.
is_active: true
project_type: 1
param_groups:
- name: inputs
  params:
  - name: dataset
    description: Dataset with images which will be stitched onto background images.
    value: null
    data_type: dataset
    required: true
  - name: backgroundDataset
    description: Images which will serve as the background for images from the other
      dataset.
    value: null
    data_type: dataset
    required: true
- name: outputs
  params:
  - name: outputDataset
    description: The output image dataset with the generated images.
    value: null
    data_type: dataset
    required: false
- name: parameters
  params:
  - name: augmentationsPerImage
    description: How many augnmented images will be generated per input image.
    value: 5
    data_type: int
    required: true
  - name: rotation
    description: Images will be rotated between 0 and this value degrees before stitching.
    value: 45
    data_type: int
    required: true
  - name: scaling
    description: Images will be scaled by this amount before stitching.
    value: 1.0
    data_type: float
    required: true
  - name: unwarp
    description: If you have used polygons for annotating an image at an angle, this
      will perspective shift the image and annotation to a rectangle. Polygon needs
      to be selected 1. top left, 2. top right, 3. bottom right, 4. bottom left.
    value: true
    data_type: bool
    required: true
  - name: excludedClasses
    description: These classes will be ignored.
    value: null
    data_type: list[str]
    required: false
  - name: useCache
    description: Whether to use cache in case it is found.
    value: false
    data_type: bool
    required: true
