id: qiime2-demultiplexing-sequences
name: 'Qiime2 -> Step 2: Demultiplexing sequences'
description: 'Multiple samples can be pooled into a single sequencing run. This reduces
  the time and

  cost of sequencing. To differentiate between these samples, each of them had a unique

  barcode injected into them before sequencing them.


  Before doing any kind of analysis on sequence data, you first need to extract

  the sample data from sequences associated with every of the barcodes. This template

  is used for doing that.


  The input is a dataset which contains miltiplexed sequences imported to Qiime2

  with the EMP Protoacol. This can be done using the Import task form the Coretex

  Qiime templates


  Output data is demultiplexed sequences which contains a separate "fastq" file

  for every sample.'
is_active: true
project_type: 11
param_groups:
- name: inputs
  params:
  - name: dataset
    description: 'A dataset which contains miltiplexed sequences imported to Qiime2

      with the EMP Protocol'
    value: null
    data_type: dataset
    required: true
- name: outputs
  params:
  - name: outputDataset
    description: The dataset to which this TaskRun will output it's results
    value: null
    data_type: dataset
    required: false
- name: parameters
  params:
  - name: barcodeColumn
    description: 'Column from sequence metadata file which containes IDs for samples.

      The values of this column are used to match sample sequences with their

      corresponding barcode.'
    value: null
    data_type: str
    required: false
