id: nlp-named-entity-recognition
name: NLP -> Named Entity Recognition
description: Searches text for provided keywords
is_active: false
project_type: 8
param_groups:
- name: inputs
  params:
  - name: dataset
    description: Dataset id that is used for fetching dataset from coretex.
    value: null
    data_type: dataset
    required: true
- name: parameters
  params:
  - name: modelPbmmUrl
    description: Deepspeech .pbmm model URL.
    value: '{RESOURCES_SERVER_URL}/experiments/deepspeech-0.8.2-models.pbmm'
    data_type: str
    required: true
  - name: modelScorerUrl
    description: Deepspeech .scorer model (model amplifier) URL.
    value: '{RESOURCES_SERVER_URL}/experiments/deepspeech-0.8.2-modelsSc.scorer'
    data_type: str
    required: true
  - name: batchSize
    description: Chunks of bytes on which transcriber will run
    value: 8196
    data_type: int
    required: true
  - name: targetWords
    description: List of words that will be searched for in the transcription.
    value: null
    data_type: list[str]
    required: false
