id: model-transfer
name: Model Transfer
description: Task template for transfering Model from one project to another one
is_active: true
project_type: 8
param_groups:
- name: parameters
  params:
  - name: sourceModelId
    description: Model id of Model which will be transfered
    value: null
    data_type: int
    required: true
  - name: sourceCredentials
    description: Coretex secret which contains credentials used for accessing the Model
    value: null
    data_type: str
    required: true
  - name: modelName
    description: Name of the Model in destination project, if not provided source Model name will be used
    value: null
    data_type: str
    required: false
